global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'bastion-production'
    replica: 'prometheus-1'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kubernetes API server
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

  # Kubernetes nodes
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics

  # Kubernetes pods
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - bastion
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

  # Bastion API service
  - job_name: 'bastion-api'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - bastion
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: bastion-api
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: http
    scrape_interval: 10s
    metrics_path: /metrics

  # Bastion UI service
  - job_name: 'bastion-ui'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - bastion
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: bastion-ui
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: http
    scrape_interval: 30s
    metrics_path: /api/metrics

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # NGINX Ingress Controller
  - job_name: 'nginx-ingress'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - ingress-nginx
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
        action: keep
        regex: ingress-nginx
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)
        replacement: $1:10254

  # Blackbox exporter for external monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://bastion.yourdomain.com
        - https://api.bastion.yourdomain.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Custom application metrics
  - job_name: 'bastion-simulations'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - bastion
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: simulation-.*
    scrape_interval: 5s

  # Blockchain metrics
  - job_name: 'blockchain'
    static_configs:
      - targets: ['blockchain:8545']
    metrics_path: /debug/metrics/prometheus
    scrape_interval: 30s

remote_write:
  - url: "https://prometheus-remote-write.yourdomain.com/api/v1/write"
    basic_auth:
      username: "bastion"
      password: "your-remote-write-password"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'bastion_.*|kubernetes_.*|node_.*'
        action: keep