apiVersion: v1
kind: Namespace
metadata:
  name: bastion
  labels:
    name: bastion
    app: bastion-platform
    version: v1.0.0
  annotations:
    description: "Bastion - GitHub for Clinical Trials Platform"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: bastion-quota
  namespace: bastion
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "20"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bastion-network-policy
  namespace: bastion
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: bastion
    - namespaceSelector:
        matchLabels:
          name: kube-system
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          name: bastion
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80